const uuid = require('uuid/v4')

module.exports = [
  {
    id: uuid(),
    artistType: 'Music Producer',
    displayName: 'Joyner Lucas',
    firstName: 'Joyner',
    lastName: 'Lucas',
    city: 'Everywhere',
    country: 'United States',
    email: 'fsalvador79@gmail.com',
    facebook: 'https://www.facebook.com/JoynerLucas/',
    instagram: 'https://www.instagram.com/joynerlucas/',
    twitter: 'https://twitter.com/JoynerLucas',
    soundcloud: 'https://soundcloud.com/realjoynerlucas',
    imageUrl: 'https://i1.sndcdn.com/avatars-000315839312-9y556a-t500x500.jpg',
    backgroundImageUrl: 'https://i1.sndcdn.com/visuals-000449386836-Eq5ZFz-t2480x520.jpg',
    genre: 'Hip Hop',
    followers: [],
    following: [],
    bio: 'Gary Lucas (born August 17, 1988) better known by his stage name Joyner Lucas, is an American rapper from Worcester, Massachusetts currently signed to Atlantic Records.',
    soundcloudLink1: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/229565693&color=%23000000&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>',
    soundcloudLink2: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/342333854&color=%23000000&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>',
    soundcloudLink3: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/405609489&color=%23000000&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>',
    soundcloudLink4: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/202845458&color=%23000000&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>'
  },
  {
    id: uuid(),
    artistType: 'Music Producer',
    displayName: 'Shoe Scene',
    firstName: 'Franz',
    lastName: 'Salvador',
    city: 'Irvine',
    country: 'United States',
    email: 'fsalvador79@gmail.com',
    facebook: 'https://www.facebook.com/ShoeScene/',
    instagram: 'https://www.instagram.com/ShoeScene/',
    twitter: 'https://twitter.com/shoescenemusic',
    soundcloud: 'https://soundcloud.com/shoescene',
    imageUrl: 'https://i1.sndcdn.com/avatars-000225828895-y9iuol-t500x500.jpg',
    backgroundImageUrl: '',
    genre: 'Dance',
    followers: [],
    following: [],
    bio: 'I am a producer based out of Southern California. I have been making music for about 7 years. I’ve played shows all across the globe. I’m always in search for vocalist’s to work with. Thanks for visiting my page!',
    soundcloudLink1: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/90101707&color=%23000000&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>',
    soundcloudLink2: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/108979481&color=%23000000&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>',
    soundcloudLink3: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/277565706&color=%23000000&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>'
  },
  {
    id: uuid(),
    artistType: 'Music Producer',
    displayName: 'Freddy Todd',
    firstName: 'Freddy',
    lastName: 'Todd',
    city: 'Detroit',
    country: 'Asheville',
    email: 'fsalvador79@gmail.com',
    facebook: 'https://www.facebook.com/freddytoddmusic',
    instagram: 'https://www.instagram.com/freddytoddmusic/',
    twitter: 'https://twitter.com/freddytoddmusic',
    soundcloud: 'https://soundcloud.com/freddytodd',
    imageUrl: 'https://i1.sndcdn.com/avatars-000334582793-42uh6n-t500x500.jpg',
    backgroundImageUrl: 'https://i1.sndcdn.com/visuals-000000098398-PdXfFr-t2480x520.jpg',
    genre: 'Dance',
    followers: [],
    following: [],
    bio: "Words will inevitably fail to properly describe Freddy Todd. Genre-busting could be an understatement. You can't pin him down with lexicon like lazer-bass and glitch-funk; these phrases fall way short of capturing the expressiveness, fearlessness, and space-traveling qualities of his music. Hearing his music is akin to being abducted by an extra-terrestrial cruise liner where everyone is tripping on space acid. And if you are lucky enough to witness him produce, you'll see that he fittingly looks just like the captain of said space cruiser, both hands intently gripping his electronics like the instrument panel on the flight deck.",
    soundcloudLink1: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/341351118&color=%23000000&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>',
    soundcloudLink2: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/243763957&color=%23000000&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>',
    soundcloudLink3: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/359519681&color=%23000000&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>',
    soundcloudLink4: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/485944722&color=%23000000&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>'
  },

  {
    id: uuid(),
    artistType: 'Vocalist',
    displayName: 'Empire of the Sun',
    firstName: 'Luke Steel &',
    lastName: 'Nick Littlemore',
    city: 'Perth',
    country: 'Australia',
    email: 'fsalvador79@gmail.com',
    facebook: '',
    instagram: '',
    twitter: '',
    soundcloud: '',
    imageUrl: 'https://i1.sndcdn.com/avatars-000247875613-mufa38-t500x500.jpg',
    backgroundImageUrl: 'https://i1.sndcdn.com/visuals-000039501170-r3Hj3P-t2480x520.jpg',
    genre: 'Dance',
    followers: [],
    following: [],
    bio: 'Empire of the Sun are an Australian electronic music duo from Sydney, formed in 2007. The band is a collaboration between Luke Steele, of alternative rock act The Sleepy Jackson, and Nick Littlemore, of electronic dance outfit Pnau.',
    soundcloudLink1: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/87639862&color=%23000000&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>',
    soundcloudLink2: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/255870218&color=%23000000&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>',
    soundcloudLink3: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/108632879&color=%23000000&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>'
  },
  {
    id: uuid(),
    artistType: 'Vocalist',
    displayName: 'Anuka',
    firstName: 'in ya',
    lastName: 'face',
    city: 'Amsterdam',
    country: 'Netherlands',
    email: 'fsalvador79@gmail.com',
    facebook: 'https://www.facebook.com/anukabyanuka',
    instagram: 'https://www.instagram.com/anukamusic/',
    twitter: 'https://twitter.com/anukamusic',
    soundcloud: 'https://soundcloud.com/anukamusic',
    imageUrl: 'https://i1.sndcdn.com/avatars-000478284558-v4ubtk-t500x500.jpg',
    backgroundImageUrl: 'https://i1.sndcdn.com/visuals-000007498283-f3fBq3-t2480x520.jpg',
    genre: 'Pop',
    followers: [],
    following: [],
    bio: 'R&B, Future, Chill, Trap, Hip-Hop, Rap, Vocals, Harmonies, Alternative, Electro, Soul, EDM, Neosoul, Triphop, Synthpop, House',
    soundcloudLink1: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/416420904&color=%23000000&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>',
    soundcloudLink2: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/403130292&color=%23000000&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>',
    soundcloudLink3: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/369576212&color=%23000000&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>',
    soundcloudLink4: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/283029239&color=%23000000&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>'
  },
  {
    id: uuid(),
    artistType: 'Vocalist',
    displayName: 'Logic',
    firstName: 'Robert Bryson',
    lastName: 'Hall',
    city: 'Gaithersburg',
    country: 'United States',
    email: 'fsalvador79@gmail.com',
    facebook: 'https://www.facebook.com/MindofLogic/',
    instagram: 'https://www.instagram.com/logic',
    twitter: 'https://twitter.com/logic301',
    soundcloud: 'https://soundcloud.com/logic_official',
    imageUrl: 'https://i1.sndcdn.com/artworks-8d285cc5-7523-45cc-b48d-9d1d33ebf892-0-t500x500.jpg',
    backgroundImageUrl: '',
    genre: 'Hip Hop',
    followers: [],
    following: [],
    bio: 'Sir Robert Bryson Hall II[a] (born January 22, 1990), known by his stage name Logic, is an American rapper, singer, songwriter, and record producer. Raised in Gaithersburg, Maryland, Logic developed an interest in music as a teenager, and ventured into a musical career in early 2009 releasing Logic: The Mixtape and a mixtape titled Young, Broke & Infamous in 2010. He signed with Visionary Music Group, before releasing three more mixtapes over three years.',
    soundcloudLink1: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/474439020&color=%23000000&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>',
    soundcloudLink2: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/495271689&color=%23000000&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>',
    soundcloudLink3: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/488740938&color=%23000000&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>'
  },
  {
    id: uuid(),
    artistType: 'Vocalist',
    displayName: 'Khalid',
    firstName: 'Khalid',
    lastName: 'Robinson',
    city: 'El Paso',
    country: 'United States',
    email: 'fsalvador79@gmail.com',
    facebook: 'https://www.facebook.com/thegreatkhalid',
    instagram: 'https://www.instagram.com/thegr8khalid/',
    twitter: 'https://twitter.com/thegreatkhalid',
    soundcloud: 'https://soundcloud.com/thegreatkhalid',
    imageUrl: 'https://i1.sndcdn.com/avatars-000213443309-euig6s-t500x500.jpg',
    backgroundImageUrl: 'https://i1.sndcdn.com/visuals-000177989887-Sl3Pnp-t2480x520.jpg',
    genre: 'R&B',
    followers: [],
    following: [],
    bio: 'Khalid Donnel Robinson, known mononymously as Khalid, is an American singer and songwriter. He is signed to Right Hand Music Group and RCA Records.',
    soundcloudLink1: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/488088219&color=%23000000&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>',
    soundcloudLink2: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/498539598&color=%23000000&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>',
    soundcloudLink3: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/226552376&color=%23000000&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>',
    soundcloudLink4: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/244997427&color=%23000000&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>'
  },
  {
    id: uuid(),
    artistType: 'Music Producer',
    displayName: 'Louis The Child',
    firstName: 'music that makes you happy',
    lastName: '',
    city: 'Chicago',
    country: 'United States',
    email: 'fsalvador79@gmail.com',
    facebook: 'https://www.facebook.com/LouisTheChild',
    instagram: 'https://www.instagram.com/louisthechild/',
    twitter: 'https://twitter.com/louisthechild',
    soundcloud: 'https://soundcloud.com/louisthechild',
    imageUrl: 'https://i1.sndcdn.com/avatars-000492910530-vu7aj3-t500x500.jpg',
    backgroundImageUrl: 'https://i1.sndcdn.com/visuals-000024969134-rkdMVQ-t2480x520.jpg',
    genre: 'Dance',
    followers: [],
    following: [],
    bio: 'Eric Teichner was born on September 7, 1996 to David Gerard Hauldren and Julia Hauldren. He attended one academic year at the University of Southern California before opting to take a leave and further pursue music. Hauldren primarily DJed and made mashups under the alias Haul Pass throughout 2011. Frederic Judson Kennett was born on October 19, 1997 to Jon and Anne Kennett. He focused on musical production under the alias Fatboy, while completing high school. Though both musicians were students at New Trier High School in Winnetka, (Hauldren in the class of 2015 and Kennett in the class of 2016), the two met at a Madeon concert.',
    soundcloudLink1: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/483205440&color=%23000000&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>',
    soundcloudLink2: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/470745663&color=%23000000&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>',
    soundcloudLink3: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/425472303&color=%23000000&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>',
    soundcloudLink4: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/337984986&color=%23000000&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>'
  }
]
